// Generated by tools/gen_music.py -- do not edit by hand.
//
// "Amusement park Stage" by MintoDog, CC0 (public domain).
// https://opengameart.org/sites/default/files/amusement_park_stage_bpm150.ogg

#pragma once

#include <cstddef>

namespace cashyphus::audio::musicdata {

constexpr int SAMPLE_RATE  = 22050;
constexpr int SAMPLE_COUNT = 282624;

extern const short PCM[SAMPLE_COUNT];

} // namespace cashyphus::audio::musicdata
