#!/usr/bin/env python3
"""Bake a BDF bitmap font into a tiny C++ table.

The UI has to read as 16-bit pixel art. Drawing with raylib's built-in font
(smooth, vector-ish) is the single biggest reason it does not, so the game
ships a real pixel face instead.

The BDF is parsed *here* -- once, by hand -- and committed as a bit-packed
table. The build itself needs no Python, which keeps CI and the Emscripten
job exactly as they were.

Source font : Retro Pixel Arcade 8px, by TakWolf
              SIL Open Font License 1.1 (see assets/fonts/LICENSE-OFL)
              https://github.com/TakWolf/retro-pixel-font
Input       : assets/fonts/retro-pixel-arcade.bdf
Output      : src/render/font_data.hpp

Usage:
    python3 tools/gen_font.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "fonts" / "retro-pixel-arcade.bdf"
DST = ROOT / "src" / "render" / "font_data.hpp"

FIRST_CHAR = 32
LAST_CHAR = 126

# The cell every glyph is padded into. Taken from the font's own
# FONTBOUNDINGBOX (8x12) and FONT_ASCENT (9), so a glyph's box drops into the
# cell at (x_off, BASELINE - y_off - height) with no further arithmetic.
CELL_W = 8
CELL_H = 12
BASELINE = 9


def parse_bdf(text: str):
    """Yield (encoding, x_off, y_off, width, height, [row_bytes])."""
    encoding = None
    bbx = None
    rows: list[int] = []
    in_bitmap = False

    for raw in text.splitlines():
        line = raw.strip()
        if line.startswith("ENCODING"):
            encoding = int(line.split()[1])
        elif line.startswith("BBX"):
            parts = line.split()
            bbx = (int(parts[3]), int(parts[4]), int(parts[1]), int(parts[2]))
        elif line == "BITMAP":
            in_bitmap = True
            rows = []
        elif line == "ENDCHAR":
            if encoding is not None and bbx is not None:
                x_off, y_off, w, h = bbx
                yield encoding, x_off, y_off, w, h, rows
            encoding = None
            bbx = None
            in_bitmap = False
        elif in_bitmap and line:
            # Long rows are split across several bytes; for an 8px-wide face
            # this is always a single byte, but parse the general case.
            rows.append(int(line, 16))


def bake() -> dict[int, list[int]]:
    """Return {char: [CELL_H bytes]}, each byte one pixel row, MSB leftmost."""
    glyphs: dict[int, list[int]] = {}

    for enc, x_off, y_off, w, h, rows in parse_bdf(SRC.read_text(encoding="utf-8", errors="replace")):
        if not (FIRST_CHAR <= enc <= LAST_CHAR):
            continue
        if w > CELL_W:
            raise SystemExit(f"glyph {enc} is {w}px wide, cell is only {CELL_W}")

        cell = [0] * CELL_H
        top = BASELINE - y_off - h
        for r in range(h):
            row = top + r
            if not (0 <= row < CELL_H):
                continue
            # A BDF row stores the glyph's pixels in the most significant bits
            # (a w-bit field, left-justified in the row's byte(s)). Shifting the
            # row right by x_off lands them at the correct cell column.
            byte = rows[r] if r < len(rows) else 0
            byte >>= x_off
            cell[row] |= byte & 0xFF
        glyphs[enc] = cell

    missing = [c for c in range(FIRST_CHAR, LAST_CHAR + 1) if c not in glyphs]
    if missing:
        raise SystemExit("font is missing: " + " ".join(chr(c) for c in missing))
    return glyphs


def emit(glyphs: dict[int, list[int]]) -> str:
    count = LAST_CHAR - FIRST_CHAR + 1
    out = [
        "// Generated by tools/gen_font.py -- do not edit by hand.",
        "//",
        "// Retro Pixel Arcade 8px, by TakWolf.",
        "// SIL Open Font License 1.1 -- see assets/fonts/LICENSE-OFL.",
        "// https://github.com/TakWolf/retro-pixel-font",
        "//",
        "// One byte per pixel row, most significant bit leftmost. Rows are the",
        f"// full {CELL_H}px cell; the baseline is row {BASELINE}.",
        "",
        "#pragma once",
        "",
        "namespace cashyphus::art::fontdata {",
        "",
        f"constexpr int FIRST_CHAR = {FIRST_CHAR};",
        f"constexpr int LAST_CHAR  = {LAST_CHAR};",
        f"constexpr int CELL_W     = {CELL_W};",
        f"constexpr int CELL_H     = {CELL_H};",
        f"constexpr int BASELINE   = {BASELINE};",
        f"constexpr int GLYPH_COUNT = {count};",
        "",
        "inline constexpr unsigned char GLYPHS[GLYPH_COUNT][CELL_H] = {",
    ]
    for c in range(FIRST_CHAR, LAST_CHAR + 1):
        cell = glyphs[c]
        shown = "".join("#" if b & 0x80 else "." for b in cell)
        body = ", ".join(f"0x{b:02X}" for b in cell)
        out.append(f"    {{ {body} }},  // '{chr(c)}'  {shown}  (rows top->bottom)")
    out += ["};", "", "} // namespace cashyphus::art::fontdata", ""]
    return "\n".join(out)


def main() -> int:
    if not SRC.exists():
        print(f"missing {SRC}", file=sys.stderr)
        return 1
    glyphs = bake()
    DST.write_text(emit(glyphs), encoding="utf-8")
    print(f"wrote {DST.relative_to(ROOT)}  ({len(glyphs)} glyphs, {CELL_W}x{CELL_H} cells)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
